<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQ6EN1hJ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQ6EN1hJ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQ6EN1hJ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQ6EN1hJ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQ6EN1hJ\App_KernelDevDebugContainer([
    'container.build_hash' => 'Q6EN1hJ',
    'container.build_id' => '264bf7c1',
    'container.build_time' => 1655051415,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQ6EN1hJ');
