<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'models_page' => [[], ['_controller' => 'App\\Controller\\AdminController::modelsAction'], [], [['text', '/admin/models']], [], [], []],
    'edit_model' => [['id'], ['_controller' => 'App\\Controller\\AdminController::editModel'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/admin/model']], [], [], []],
    'delete_model' => [['id'], ['_controller' => 'App\\Controller\\AdminController::deleteModel'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/admin/delete_model']], [], [], []],
    'edit_save_model' => [['id'], ['_controller' => 'App\\Controller\\AdminController::editSaveModel'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/admin/model']], [], [], []],
    'users_page' => [[], ['_controller' => 'App\\Controller\\AdminController::usersAction'], [], [['text', '/admin/users']], [], [], []],
    'stamps_page' => [[], ['_controller' => 'App\\Controller\\AdminController::stampsAction'], [], [['text', '/admin/stamps']], [], [], []],
    'edit_stamp' => [['id'], ['_controller' => 'App\\Controller\\AdminController::editStamp'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/admin/stamp']], [], [], []],
    'delete_stamp' => [['id'], ['_controller' => 'App\\Controller\\AdminController::deleteStamp'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/admin/delete_stamp']], [], [], []],
    'edit_save_stamp' => [['id'], ['_controller' => 'App\\Controller\\AdminController::editSaveStamp'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/admin/stamp']], [], [], []],
    'app_register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/register']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], [], []],
    'index_page' => [[], ['_controller' => 'App\\Controller\\indexController::indexAction'], [], [['text', '/']], [], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
];
